### ISSUE TITLE
Unable to break a string type into characters

### ISSUE THREAD

**Issue by ChrisRx** [ktravis/verse#1]
The string type does not feature the subscript operation making it difficult to gain access to individual characters.  When using a for loop for iteration on a string type it returns a `u8`, but currently cannot figure out how to cast this into a string type.  What I have currently is this:

```
for c in fmt {
    write(1, itoa(c as int), 1);
}
```

and given the format string `"%s %s\n"` it returns: `3133110`.

I'm not sure but this may be related to multiple issues, one with string types, another with how the for loop works, and another with `u8` to `int` casting.

I think the desired feature would probably be string slices, but I think even subscript access that allocates new strings would be extremely helpful in this case.  A request I have that may help during this stage of development is to either reduce restrictions on casting or allow an "unwise" cast operator that helps to fulfill the type system in scenarios like this where features are either not there yet or not working as intended.  I think it could make working backwards from problems while building stdlib packages a bit easier.

Lastly, FIRST!

**Comment by ktravis** [comment]
Looks like there is a problem with codegen for the string indexing, I don't think that will be hard to fix. I can add some kind of identifier for doing an unwise cast as well just to make the compiler not complain until something more formal is decided.
