### ISSUE TITLE
Proposal: Move all C source into the src/compiler folder

### ISSUE THREAD

**Issue by ChrisRx** [ktravis/verse#15]
New additions such as the `src/array` and `src/hashmap` fit better logically in the `src/compiler/` folder.  The mixing of C libraries with the verse standard library reduces the ability for the standard library to use that package namespace without also putting those files in with that C library (and they may use the same name and not be related).  It wouldn't be a big change, just moving `src/array` to `src/compiler/array`, for example.  It may also be good to go ahead and prefix the `src/compiler` folder by renaming it to be `src/ccompiler`.

**Comment by ktravis** [comment]
That's a good idea, I had decided to do it a while back but forgot to actually make the move before committing. I will move those.

**Comment by ktravis** [comment]
Fixed with 54c83df4724f1f2f593695bcc482e9f9e9bc3282
