### ISSUE TITLE
Generic structs with no members crash the compiler

### ISSUE THREAD

**Issue by ChrisRx** [ktravis/verse#16]
To reproduce:

```
type Empty: struct(T) {
};

fn main() -> int {
    e: Empty(string);
    return 0;
}
```

**Comment by ChrisRx** [comment]
There was some other behavior related to some combination of use of semi-colons and not using semi-colons that may have been either related to this or I observed it while figuring out what was causing this compiler bug.  If I can figure out a definitive way to reproduce I will post those as well, but I imagine it could very possibly be related to the same core bug (which is why I mention it).

**Comment by ktravis** [comment]
Good catch, this actually revealed an issue with type-checking as well (parameters were not accounted for unless they were actually used in the members of the struct) which has been fixed.
