### ISSUE TITLE
Operator '+' is valid only for numeric or string arguments, not for type 'string'.

### ISSUE THREAD

**Issue by ChrisRx** [ktravis/verse#2]
Running the following:

```
for c in fmt {
    write(1, "Char: " + c, 1);
}
```

produces the error:

```
Operator '+' is valid only for numeric or string arguments, not for type 'string'.
```

The expected error here would be 

```
Operator '+' is valid only for numeric or string arguments, not for type 'u8'.
```

Or possibly no error at all since u8 could be considered a numeric and a valid operation.

**Comment by ktravis** [comment]
Error improved in latest commit. Will add some simple facility for coercing a u8 into a string so that concatenation is straightforward.

**Comment by ChrisRx** [comment]
I think this was fixed so I'm closing the issue.
